### ISSUE TITLE
Setting g:c_nl_before_curlyB doesn't seem to take effect.

### ISSUE THREAD

**Issue by troycurtisjr** [LucHermitte/lh-cpp#1]
I've been trying out your extensive plugin, but notice that no matter what value I set 'g:c_nl_before_curlyB'  to, or where I put the setting, I always get:

if () {
}

instead of my desired:
if ()
{
}

Thanks!

**Comment by LucHermitte** [comment]
These options have been deprecated in favour of [`:AddStyle`](https://github.com/LucHermitte/lh-dev#formatting-of-brackets-characters)
You'll have to use it either from an `after` c or c++ ftplugin, or from a [local_vimrc](https://github.com/LucHermitte/local_vimrc)

-> `:AddStyle { -b \\n{\\n -prio=10 -ft=c`

And I'll have to update the documentation.
BTW, I see a bug in lh-dev `:AddStyle`, priority isn't updated if it has been forgotten the first time.

**Comment by troycurtisjr** [comment]
Ah! Excellent. I'll give it a go. Don't remember seeing that anywhere, but
then again looking at your plugin made me think that maybe I don't actually
know vim script after all. ;)

**Comment by LucHermitte** [comment]
It'll be hard to remember seeing that somewhere:
 * I forgot to document it (as many other things) ^^'
 * You'll have to follow `lh#dev#style#apply()` to see instances of `AddStyle` in the source code.
