### ISSUE TITLE
Use #pragma once instead of #ifndef in c++ template

### ISSUE THREAD

**Issue by AndreasAZiegler** [LucHermitte/lh-cpp#12]
As I'm using ```#pragma once``` instead of ```#ifndef```, I tried to change the C++ template file ```cpp_BuildTemplates.vim``` on lines 227, 228 and 327, 328 accordingly. Unfortunately this does not seem to work. What did I miss?

**Comment by LucHermitte** [comment]
`cpp_BuildTemplates.vim` is quite old stuff. I'm not sure that part is used anywhere any more. I'll need to eventually clean up this dead code.

What about overriding [`after/template/c/internals/c-header.template`](https://github.com/LucHermitte/mu-template/blob/master/after/template/c/internals/c-header.template) from mu-template?

You should just have to drop the replacement in `~/.vim/template/c/internals/` if I remember correctly. If you prefer, I can take care of this through an option.

**Comment by AndreasAZiegler** [comment]
I would highly appreciate if you could take car of this as I'm not yet that familiar with your plugin.
